<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" />
		<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WriteAheadLog\WriteAheadLog.csproj" />
	</ItemGroup>

</Project>
